//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tanki.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TANKI_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_INSTRUKCJA                  130
#define IDD_CREDITS                     131
#define IDD_IP                          132
#define IDD_DOLACZ                      133
#define IDD_GRA                         134
#define IDD_CZAT                        135
#define IDD_DIALOG1                     137
#define IDD_MENU                        137
#define BM_TANK_MASK                    140
#define BM_BULLETS                      141
#define BM_BULLETS_MASK                 142
#define BM_BONUS                        143
#define BM_BONUS_MASK                   144
#define BM_GRASS                        145
#define BM_OBJECT                       146
#define BM_OBJECT_MASK                  147
#define BM_GRASS_MASK                   148
#define BM_MENU_DOWN                    149
#define BM_MENU_DOWN_MASK               150
#define BM_MENU_UP                      151
#define BM_MENU_UP_MASK                 152
#define BM_VARIABLE                     153
#define BM_VARIABLE_MASK                154
#define BM_TYTUL                        155
#define BM_COLORS                       156
#define BM_CREDITS                      157
#define BM_INSTRUCT                     158
#define BM_TANK_ID_MASK                 161
#define IDB_BITMAP1                     162
#define IDD_DIALOG2                     163
#define IDD_WYNIKI                      163
#define BM_PLACE                        164
#define BM_INSTRUCT_MASk                165
#define BM_TYTUL_MASK                   166
#define IDB_BITMAP2                     167
#define BM_COLORS_MASK                  167
#define IDC_START                       1001
#define IDC_INSTRUKCJA                  1002
#define IDC_CREDITS                     1003
#define IDC_EDIT1                       1005
#define IDC_KOLOR1                      1006
#define IDC_KOLOR2                      1007
#define IDC_KOLOR3                      1008
#define IDC_KOLOR4                      1009
#define IDC_KOLOR5                      1010
#define IDC_KOLOR6                      1011
#define IDC_KOLOR7                      1012
#define IDC_KOLOR8                      1013
#define IDC_KOLOR9                      1014
#define IDC_KOLOR10                     1015
#define IDC_NICK                        1016
#define IDC_TXT                         1017
#define IDC_BUTTON2                     1021
#define BM_TANK                         1021
#define IDC_LIST1                       1022
#define IDC_LISTA                       1023
#define BM_TANK_ID                      12324

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
