//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TankiServ.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TANKISERV_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_SERV                        130
#define IDD_MAPA                        131
#define IDC_FRAGS                       1001
#define IDC_GRACZE                      1002
#define IDC_CZATBOX                     1004
#define IDC_BUTTON1                     1005
#define IDC_MAPA                        1005
#define IDC_MAP1                        1006
#define IDC_MAP2                        1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
